defmodule LunchMoney.Transactions.Transaction do
  @type tag :: %{
          id: integer(),
          name: String.t()
        }

  @type t :: %__MODULE__{
          id: integer(),
          date: String.t(),
          payee: String.t(),
          amount: String.t(),
          currency: String.t(),
          to_base: float(),
          category_id: integer() | nil,
          category_name: String.t() | nil,
          category_group_id: integer() | nil,
          category_group_name: String.t() | nil,
          is_income: boolean(),
          exclude_from_budget: boolean(),
          exclude_from_totals: boolean(),
          created_at: String.t(),
          updated_at: String.t(),
          status: String.t() | nil,
          is_pending: boolean(),
          notes: String.t() | nil,
          original_name: String.t() | nil,
          recurring_id: integer() | nil,
          recurring_payee: String.t() | nil,
          recurring_description: String.t() | nil,
          recurring_cadence: String.t() | nil,
          recurring_type: String.t() | nil,
          recurring_amount: String.t() | nil,
          recurring_currency: integer() | nil,
          parent_id: integer() | nil,
          has_children: boolean(),
          group_id: integer() | nil,
          is_group: boolean(),
          asset_id: integer() | nil,
          asset_institution_name: String.t() | nil,
          asset_name: String.t() | nil,
          asset_display_name: String.t() | nil,
          asset_status: String.t() | nil,
          plaid_account_id: integer() | nil,
          plaid_account_name: String.t() | nil,
          plaid_account_mask: String.t() | nil,
          institution_name: String.t() | nil,
          plaid_account_display_name: String.t() | nil,
          plaid_metadata: String.t() | nil,
          source: String.t(),
          display_name: String.t(),
          display_notes: String.t() | nil,
          account_display_name: String.t(),
          tags: [tag()],
          children: [t()] | nil,
          external_id: String.t() | nil
        }

  defstruct [
    :id,
    :date,
    :payee,
    :amount,
    :currency,
    :to_base,
    :category_id,
    :category_name,
    :category_group_id,
    :category_group_name,
    :is_income,
    :exclude_from_budget,
    :exclude_from_totals,
    :created_at,
    :updated_at,
    :status,
    :is_pending,
    :notes,
    :original_name,
    :recurring_id,
    :recurring_payee,
    :recurring_description,
    :recurring_cadence,
    :recurring_type,
    :recurring_amount,
    :recurring_currency,
    :parent_id,
    :has_children,
    :group_id,
    :is_group,
    :asset_id,
    :asset_institution_name,
    :asset_name,
    :asset_display_name,
    :asset_status,
    :plaid_account_id,
    :plaid_account_name,
    :plaid_account_mask,
    :institution_name,
    :plaid_account_display_name,
    :plaid_metadata,
    :source,
    :display_name,
    :display_notes,
    :account_display_name,
    :tags,
    :children,
    :external_id
  ]

  alias LunchMoney.Transactions.Transactable

  @spec new(map()) :: t()
  def new(attrs) do
    Transactable.transaction(attrs)
  end
end
